version: '3.1'
# name: rabbitmq

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    ports:
      - 4369:4369
      - 5672:5672
      - 15672:15672
      - 25672:25672
    volumes: 
      - ./data:/var/lib/rabbitmq
      - ./log:/var/log/rabbitmq/log
    restart: always
