version: '3.1'
name: nginx

services:
  nginx:
    container_name: nginx
    image: nginx:1.24
    ports:
      - 80:80
      - 6389:6389
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf 
      - ./html:/etc/nginx/html 
    restart: always
