version: '3.1'
name: jenkins

services:
  jenkins:
    image: jenkins/jenkins:2.401.1-lts-jdk11
    container_name: jenkins
    ports:
      - 8000:8080
      - 50000:50000
    volumes:
      - ./home:/var/jenkins_home
    deploy:
        resources:
            limits:
                memory: 2058m # 设置内存使用限制
    user: root
